### ISSUE TITLE
Closing head tag in the wrong area

### ISSUE THREAD

**Issue by April6804** [RoderickZemenar/Mixtape1#3]
https://github.com/RoderickZemenar/Mixtape1/blob/01fde2c5fa238932742db322d8fb835211532133/index.html#L138

This was supposed to be higher up in the HTML file. There is an opening head tag, then the opening and closing title tags, and then the closing head tag should be next.
Make sure to fix this.

**Comment by RoderickZemenar** [comment]
> https://github.com/RoderickZemenar/Mixtape1/blob/01fde2c5fa238932742db322d8fb835211532133/index.html#L138
> 
> This was supposed to be higher up in the HTML file. There is an opening head tag, then the opening and closing title tags, and then the closing head tag should be next.
> Make sure to fix this.

I'm not sure I understand.
